#!/usr/bin/env bash
set -euo pipefail

# ДЕ ЩО ЛЕЖИТЬ
OFFICIAL_DIR="/home/pinokew/koha-official/debian/templates"
TARGET_DIR="/home/pinokew/koha-doker/files/docker/templates"

echo "Using OFFICIAL_DIR = $OFFICIAL_DIR"
echo "Using TARGET_DIR   = $TARGET_DIR"
mkdir -p "$TARGET_DIR"

echo
echo "=== 1) Генеруємо koha-common.cnf (KDV, env-based) ==="
cat > "$TARGET_DIR/koha-common.cnf" << 'EOF'
# Autogenerated from upstream debian/templates/koha-common.conf for KDV Docker.
# Тут нам потрібен лише MySQL client профіль для koha-* CLI всередині контейнера.

[client]
host     = ${MYSQL_SERVER}
user     = root
password = ${DB_ROOT_PASS}
EOF
echo "  -> $TARGET_DIR/koha-common.cnf оновлено"

echo
echo "=== 2) Патчимо koha-sites.conf з офіційного шаблону ==="
cp "$OFFICIAL_DIR/koha-sites.conf" "$TARGET_DIR/koha-sites.conf"

# Підставляємо значення через змінні середовища (KOHA_* + ZEBRA_* + MEMCACHED)
sed -i '
s/^DOMAIN=.*/DOMAIN="${KOHA_DOMAIN}"/
s/^INTRAPORT=.*/INTRAPORT="${KOHA_INTRANET_PORT}"/
s/^INTRAPREFIX=.*/INTRAPREFIX="${KOHA_INTRANET_PREFIX}"/
s/^INTRASUFFIX=.*/INTRASUFFIX="${KOHA_INTRANET_SUFFIX}"/
s/^OPACPORT=.*/OPACPORT="${KOHA_OPAC_PORT}"/
s/^OPACPREFIX=.*/OPACPREFIX="${KOHA_OPAC_PREFIX}"/
s/^OPACSUFFIX=.*/OPACSUFFIX="${KOHA_OPAC_SUFFIX}"/
s/^ZEBRA_MARC_FORMAT=.*/ZEBRA_MARC_FORMAT="${ZEBRA_MARC_FORMAT}"/
s/^ZEBRA_LANGUAGE=.*/ZEBRA_LANGUAGE="${ZEBRA_LANGUAGE}"/
s/^USE_MEMCACHED=.*/USE_MEMCACHED="${USE_MEMCACHED}"/
s/^MEMCACHED_SERVERS=.*/MEMCACHED_SERVERS="${MEMCACHED_SERVERS}"/
' "$TARGET_DIR/koha-sites.conf"

# Якщо в офіційному файлі немає BIBLIOS_INDEXING_MODE / AUTHORITIES_INDEXING_MODE — додаємо в кінці
if ! grep -q 'BIBLIOS_INDEXING_MODE' "$TARGET_DIR/koha-sites.conf"; then
  cat >> "$TARGET_DIR/koha-sites.conf" << 'EOF'

# KDV: explicit indexing modes (навіть якщо фактично використовуємо Elasticsearch)
BIBLIOS_INDEXING_MODE="${BIBLIOS_INDEXING_MODE}"
AUTHORITIES_INDEXING_MODE="${AUTHORITIES_INDEXING_MODE}"
EOF
fi

echo "  -> $TARGET_DIR/koha-sites.conf оновлено"

echo
echo "=== 3) Патчимо SIPconfig.xml (accounts/institutions через env) ==="
cp "$OFFICIAL_DIR/SIPconfig.xml" "$TARGET_DIR/SIPconfig.xml"

# Замінюємо весь блок <accounts>...</accounts> на плейсхолдер ${SIP_CONF_ACCOUNTS}
perl -0pi -e 's|<accounts>.*?</accounts>|  <accounts>\n      ${SIP_CONF_ACCOUNTS}\n  </accounts>|s' \
  "$TARGET_DIR/SIPconfig.xml"

# Замінюємо весь блок <institutions>...</institutions> на плейсхолдер ${SIP_CONF_LIBS}
perl -0pi -e 's|<institutions>.*?</institutions>|<institutions>\n    ${SIP_CONF_LIBS}\n</institutions>|s' \
  "$TARGET_DIR/SIPconfig.xml"

echo "  -> $TARGET_DIR/SIPconfig.xml оновлено"

echo
echo "=== 4) Копіюємо koha-conf-site.xml.in (поки без патчів, але під контролем репо) ==="
cp "$OFFICIAL_DIR/koha-conf-site.xml.in" "$TARGET_DIR/koha-conf-site.xml.in"
echo "  -> $TARGET_DIR/koha-conf-site.xml.in оновлено (1:1 з upstream)"

echo
echo "=== DONE: поточний вміст TARGET_DIR ==="
ls -1 "$TARGET_DIR"
echo
echo "Готово. Тепер ці шаблони можна використовувати в Docker build."
